### ISSUE TITLE
Command set_lumberjack_points doesn't work

### ISSUE THREAD

**Issue by IITFA** [joe7575/lumberjack#12]
So I just downloaded the mod (from releases) and put it on my server and went to set my points to finish testing out the mod only to realize that the key command is not working as expected.

![lumberjackbug](https://user-images.githubusercontent.com/28982837/124371967-c6774180-dc54-11eb-961d-c0bc2b6ab94a.png)

**Comment by joe7575** [comment]
Please try the latest version: https://github.com/joe7575/lumberjack/archive/refs/heads/master.zip
