### ISSUE TITLE
Mod toolrank compatibility

### ISSUE THREAD

**Issue by mazes-80** [joe7575/lumberjack#13]
[toolranks](https://notabug.org/TenPlus1/toolranks) mod allows to count amount of times a tool has been used, to set rankings for tools

From the moment lumberjack unlock full tree capacity the number of time tool is used is seen by toolranks as 1, no matter how many logs were harvested, it should match this number. add_wear is called accordingly to number of harvested logs

**Comment by joe7575** [comment]
I added a few lines. I don't know toolranks. So please check if it behaves as expected. 
(It should also fix the screwdriver issue)

**Comment by mazes-80** [comment]
For the screwdriver it works

Look at my PR #15

**Comment by joe7575** [comment]
Thanks for the PRs
