### ISSUE TITLE
Digtron compatibilty

### ISSUE THREAD

**Issue by mazes-80** [joe7575/lumberjack#21]
I was trying another approach to detect if can_dig is called from digtron mod, but it failed :(

In the process I got some strange behavior: parts of the tree removed with digtron does not seem to affect the ability to cut the whole tree. I mean the block digged by digtron as been replaced by air but still is valid when it comes to recurse the tree.

Schematic (A: air, T: tree stem)
`TAT                TAT                   AAA`
`ATA                ATA                   AAA`
`ATA  -> digtron -> AAA                   AAA`
`ATA                ATA -> chop this T -> AAA`

Shouldn't tree top still be there or Is it intended ?
Does digtron fail skip removing some metadata ?

**Comment by joe7575** [comment]
> Shouldn't tree top still be there or Is it intended ?

This is intentional. See https://github.com/joe7575/lumberjack/blob/master/init.lua#L123
