### ISSUE TITLE
Config doesn't work on servers

### ISSUE THREAD

**Issue by FlitPix** [joe7575/lumberjack#22]
Configuring `lumberjack_points` doesn't appear to work on a multiplayer server.

I've attempted setting it in minetest.conf (`lumberjack_points = 0`) and in settingtypes.txt (`lumberjack_points (needed points to get lumberjack privs) int 0`); neither seem to work.

If this is not how server admins are intended to configure the mod for a server, documentation should be provided.

**Comment by joe7575** [comment]
It should work like this. However, this only works for new players as the value is stored in player meta data. For existing players only the chat command works

**Comment by FlitPix** [comment]
Ahh, that makes sense. How would I grant the priv to existing players, then? Would I have to just grant the required points?

**Comment by joe7575** [comment]
Yes, with `/set_lumberjack_points Tom 0` you grant the privs to Tom.

**Comment by FlitPix** [comment]
Understood, in that case there's no issue here. Thanks for clarifying!
