### ISSUE TITLE
Unable to dig trees without axe

### ISSUE THREAD

**Issue by GeorgeZack** [joe7575/lumberjack#7]
(All of this was tested on a server)

When trying to dig a tree after spawning in for the first time, I received a message: "[Lumberjack Mod] You have to use an axe"

I understand the point of the mod is to require players to use axes, but when first spawning in, and having the Lumberjack privs, I am unable to even make myself an axe by punching some trees. Is there a configuration around this issue?

I believe this comes from the method located on line `244` in `init.lua`

**Comment by joe7575** [comment]
I see this as a misconfiguration on the server you are talking about. 
According to the readme:

> New player normally will not get the necessary privs immediately, they have to harvest the tree from the top, block by block "to improve their skills".

With this default configuration, you have the possibility to dig trees to be able to craft an axe. If you server admin uses a different configuration, he/she as to provide you the necessary startup items.

**Comment by GeorgeZack** [comment]
I am the admin, I have been experimenting with the mod. The issue is if a player who has received the privilege, yet loses an axe (say from dying or from it breaking) and does not have access to another axe or the resources to craft an axe, it is impossible to gather more wood from trees. The top down cutting feature doesn't work.

Admittedly, this is an edge case. There are easy workarounds for it.

**Comment by joe7575** [comment]
This seems like a worst case scenario, but even then:
- you can ask other players to give you a piece of wood
- you can harvest bush stems to get wood
- you can enter the server with a second account to harvest wood
