### ISSUE TITLE
POINT system is not working

### ISSUE THREAD

**Issue by daretmavi** [joe7575/lumberjack#9]
Player get the point intermediately. because in `local function check_points(player)` the function `player_attributes:get_float("lumberjack_tree_points")` returns 0 it key is not present - with is not.

Then the check is successful and player get the privileges.
```
...
elseif points == 0 then
			local privs = minetest.get_player_privs(player:get_player_name())
			privs.lumberjack = true
...
```

**Comment by joe7575** [comment]
Thanks for reporting. I hopefully fixed it, give it a try...
